### DISCUSSION TITLE
Unhandled Exception: System.InvalidOperationException: A suitable constructor for type 'Amazon.Lambda.AspNetCoreServer.Hosting.Internal.APIGatewayHttpApiV2LambdaRuntimeSupportServer' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

### DISCUSSION THREAD

**Discussion by noopd13** [aws/aws-lambda-dotnet#1600] [Q&A] [answered]
Hello everyone , 

I'm in the process of configuring a .NET 7 AOT minimal API that's integrated with a lambda function URL. However, an exception is thrown each time the API endpoint is accessed. Any assistance would be appreciated.

`Unhandled Exception: System.InvalidOperationException: A suitable constructor for type 'Amazon.Lambda.AspNetCoreServer.Hosting.Internal.APIGatewayHttpApiV2LambdaRuntimeSupportServer' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.`

program.cs

```
using Microsoft.EntityFrameworkCore;
using ReservationWebhook;
using ReservationWebhook.Models;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers();
// Add AWS Lambda support. When application is run in Lambda Kestrel is swapped out as the web server with Amazon.Lambda.AspNetCoreServer. This
// package will act as the webserver translating request and responses between the Lambda event source and ASP.NET Core.
builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);

var app = builder.Build();


app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.MapGet("/", () => "Hello World!");

app.Run();

```
project.csproj
```

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improvement cold starts. -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
    <StripSymbols>true</StripSymbols>
    <OutputType>Exe</OutputType>
    <AssemblyName>bootstrap</AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.13" />
  </ItemGroup>

  <ItemGroup>
   <TrimmerRootAssembly Include="Amazon.Lambda.AspNetCoreServer.Hosting" />
   <TrimmerRootAssembly Include="Amazon.Lambda.AspNetCoreServer" />
   <TrimmerRootAssembly Include="Microsoft.EntityFrameworkCore.SqlServer" />
 </ItemGroup>
</Project>
```

SAM .yml

```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses the ASP.NET Core framework running in
  Amazon Lambda.
Parameters: {}
Conditions: {}
Resources:
  AspNetCoreFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: SampleWebhook
      CodeUri: ''
      MemorySize: 256
      Timeout: 30
      FunctionUrlConfig:
        AuthType: NONE
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: dotnet7

```
