### ISSUE TITLE
CICD lambda on AWS using dotnet lambda deploy

### ISSUE THREAD

**Issue by rui-infotrack** [aws/aws-lambda-dotnet#107]
I can use AWS CodeBuild + CodePipeline to build lambda package (by invoke dotnet package), but I'm wondering how do I make the deployment work in CodeBuild.

I'm guessing, in buildspec.yml, I can add a command in build section like below?

```
version: 0.1

phases:
  build:
    commands:
      - dotnet lambda deploy-function -cfg ./src/my-lambda.config.json
```

This might be a dumb question... I'm just new to lambda still : )
