### ISSUE TITLE
DefaultLambdaJsonSerializer ignores custom input (aws lambda net6)

### ISSUE THREAD

**Issue by Rodriguevb** [aws/aws-lambda-dotnet#1227]
### Describe the bug

Following the documentation for aws lambda net6:
- https://docs.aws.amazon.com/lambda/latest/dg/csharp-handler.html
- or small tutorial https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

The simple Top-level lambda code below ignores my simple POST request. The console displays `>;0` instead of `>Simple text;8612` Why ? Did I forget a package? My api is `AWS::Serverless::HttpApi`

```
using Amazon.Lambda.Core;
using Amazon.Lambda.RuntimeSupport;
using Amazon.Lambda.Serialization.SystemTextJson;
var handler = async (LambdaInput input, ILambdaContext context) =>
{
	Console.Write($">{input.Property1};{input.Property2}");
}

await LambdaBootstrapBuilder.Create(handler, new DefaultLambdaJsonSerializer())
	.Build()
	.RunAsync();
```

```
public class LambdaInput
{
	public string Property1 { get; set; } = "";
	public int Property2 { get; set; }
}
```

The `test.http`
```
POST https://my.api.com/request
Content-Type: application/json

{
	"Property1": "Simple text",
	"Property2": 8612
}
```

### Expected Behavior

I expected to receive the object deserialized correctly by the `DefaultLambdaJsonSerializer()` with the values "Simple text" and 8612.

### Current Behavior

 The console displays `>;0` instead of `>Simple text;8612`

### Reproduction Steps

The Api:
```
Resources:
  MyApi:
    Type: 'AWS::Serverless::HttpApi'
    Description: 'MyApi description'
    Properties:
      CorsConfiguration:
        AllowCredentials: True
        AllowHeaders:
          - "content-type"
        AllowMethods:
          - "*"
        AllowOrigins:
          - 'https://my.api.com'
  LambdaGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: dotnet6
      Architectures:
        - 'x86_64' # 'arm64'
      Timeout: 300
      MemorySize: 512
      Role: !GetAtt RoleLambda.Arn
      CodeUri: 'core/Lambda.Code'
      Handler: 'Lambda.Code'
      Events:
        LambdaGetResults:
          Type: 'HttpApi'
          Properties:
            ApiId: !Ref MyApi
            Path: '/request'
            Method: 'post'
```

### AWS .NET SDK and/or Package version used

```
Amazon.Lambda.Core 2.1.0
Amazon.Lambda.RuntimeSupport 1.8.2
Amazon.Lambda.Serialization.SystemTextJson 2.3.0
AWSSDK.Core 3.7.12.3
```

### Targeted .NET Platform

.NET 6

### Operating System and version

AWS::Serverless::Function
