### ISSUE TITLE
Lambda annotations YAML generation does not support short hand syntax

### ISSUE THREAD

**Issue by jaknor** [aws/aws-lambda-dotnet#1340]
### Describe the bug

When using Lambda Annotations we get a build error whenever our Cloudformation contains any of the short hand Cloudformation syntax, such as `!Ref`

### Expected Behavior

The solution should build without errors

### Current Behavior

We receive the error message

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AWSLambda0001	This is a bug. Please run the build with detailed verbosity (dotnet build --verbosity detailed) and file a bug at https://github.com/aws/aws-lambda-dotnet with the build output and stack trace Encountered an unresolved tag '!Ref'   at YamlDotNet.Serialization.NodeTypeResolvers.PreventUnknownTagsNodeTypeResolver.YamlDotNet.Serialization.INodeTypeResolver.Resolve(NodeEvent nodeEvent, Type& currentType)	dotnet_lambda
```

### Reproduction Steps

Using lambda annotations define a lambda in code like below
```
[LambdaFunction(Name = "LambdaWithShortHandYaml")]
[RestApi(LambdaHttpMethod.Get, "/hello-world")]
public async Task LambdaWithShortHandYaml()
{
    await Task.Delay(1);
}
```
Then modify the Cloudformation to add an environment variable using the short hand synxax
```
  LambdaWithShortHandYaml:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: dotnet_lambda::dotnet_lambda.Functions.Api_LambdaWithShortHandYaml_Generated::LambdaWithShortHandYaml
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET
      Environment:
        Variables:
          MyVariable: !Ref Variable
```

Attempt to build the solution

### Possible Solution

It seems you are using YamlDotNet for parsing the YAML. They have an [open issue](https://github.com/aaubry/YamlDotNet/issues/521) to support Cloudformation short hand syntax which if finished would probably fix the issue

### Additional Information/Context

This fails even if disconnect the lambda in cloudformation from the annotations framework by removing the code below
```
Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPut
``` 

It does appear that we can use the short hand syntax in the `Globals` section.

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.Annotations" Version="0.8.0-preview" />

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10
