### ISSUE TITLE
How do you deploy to a specific stage in API Gateway

### ISSUE THREAD

**Issue by drobison** [aws/aws-lambda-dotnet#167]
I am developing an API Gateway and Lambda function with AWS Lambda Templates with .NET Web API. When publishing to AWS, the API is deployed to the production stage. How can I configure which environment to deploy to?

**Comment by Shockolate** [comment]
Pass the environment into the template as a Template Parameter.
```yaml
Parameters:  
  Environment:
    Type: String
    Default: dev
    Description: Enter the environment. Default is dev

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Environment
      ... etc

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      ... etc
```
