### ISSUE TITLE
IOutputCache does not work with Lambda runtime

### ISSUE THREAD

**Issue by tvytrykush** [aws/aws-lambda-dotnet#1702]
### Describe the bug

When using IOutputCache feature of asp.net core the cached value is not populated from the response body and is empty

### Expected Behavior

Response's cache value is properly cached from response body alongside the key(that is cached properly)

### Current Behavior

Because empty value is being cached with valid key - on subsequent requests using same path the response body is going to be empty.

### Reproduction Steps

1. Create new project using "Lambda ASP.NET Core Web API" template
2. Get redis instance running
3. Add Output cache to service collection in Startup:
```C#
services
            .AddOutputCache(options =>
                options.AddBasePolicy(builder =>
                        builder.AddPolicy<OutputCacheRedisPolicy>().Cache(),
                    true))
            .AddStackExchangeRedisOutputCache(opts =>
            {
                opts.Configuration = "localhost:<redis-port>";
                opts.InstanceName = "lambda";
            });
```
4. Add `app.UseOutputCache();` before app.UseEndpoints in Configure
5. Add IOutputCachePolicy implementation class into project:
```C#
public class OutputCacheRedisPolicy : IOutputCachePolicy
{
    private const string TagPrefix = "response-cache-";
    private static readonly TimeSpan CacheExpirationPeriod = TimeSpan.FromMinutes(15);

    ValueTask IOutputCachePolicy.CacheRequestAsync(OutputCacheContext context, CancellationToken cancellationToken)
    {
        var attemptOutputCaching = AttemptOutputCaching(context);
        
        context.EnableOutputCaching = true;
        context.AllowCacheLookup = attemptOutputCaching;
        context.AllowCacheStorage = attemptOutputCaching;
        context.AllowLocking = true;
        context.ResponseExpirationTimeSpan = CacheExpirationPeriod;
        context.CacheVaryByRules.QueryKeys = "*";

        context.Tags.Add(TagPrefix + context.HttpContext.Request.RouteValues["controller"]);
        
        return ValueTask.CompletedTask;
    }
    
    private static bool AttemptOutputCaching(OutputCacheContext context)
    {
        var request = context.HttpContext.Request;

        return HttpMethods.IsGet(request.Method) || HttpMethods.IsHead(request.Method);
    }
    
    public ValueTask ServeFromCacheAsync(OutputCacheContext context, CancellationToken cancellation) 
        => ValueTask.CompletedTask;

    public ValueTask ServeResponseAsync(OutputCacheContext context, CancellationToken cancellation)
    {
        var response = context.HttpContext.Response;

        // Verify existence of cookie headers
        if (!StringValues.IsNullOrEmpty(response.Headers.SetCookie))
        {
            context.AllowCacheStorage = false;
            return ValueTask.CompletedTask;
        }

        // Check response code
        if (response.StatusCode is StatusCodes.Status200OK or StatusCodes.Status301MovedPermanently)
        {
            return ValueTask.CompletedTask;
        }
        
        context.AllowCacheStorage = false;
        return ValueTask.CompletedTask;
    }
}
```
6. Run with the AWS Test Mock Tool (or any tool running within Lambda runtime)
7. Send GET request to /api/values -> value will be cached
8. Send GET request again to /api/values -> response body is empty -> value stored for cached key in redis is empty 

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer v9.0.0
Microsoft.AspNetCore.OutputCaching.StackExchangeRedis v8.0.0

### Targeted .NET Platform

.NET 8

### Operating System and version

MacOS Sonoma 14.2.1

**Comment by ashishdhingra** [comment]
@tvytrykush Good morning. I do not think you would be able to test the `IOutputCache` feature with the Lambda test tool. Lambda Test Tool is recommended for testing simple functional handlers and it would be better to use IIS/IIS Express/Kestrel to test REST endpoints. However, you could refer the guidance provided in https://github.com/aws/aws-lambda-dotnet/issues/589#issuecomment-682179425 to test API methods locally.

Have you tried testing `IOutputCache` feature after deploying to actual AWS environment and see if it works (you would need to setup Redis cluster and setup configuration accordingly, including any IAM policies)?

Thanks,
Ashish

**Comment by tvytrykush** [comment]
Hello @ashishdhingra, that's the point I wanted to emphasize here. Running same app via Kestrel works just fine and correct cache value is being stored and returned in subsequent requests. The problem only arises when running via LambdaEntryPoint and corresponding handler.

**Comment by ashishdhingra** [comment]
> I've also tried running in live AWS Lambda, but the behavior is completely the same - invalid cache value being stored.

@tvytrykush Good morning. Could you please describe your live AWS Lambda setup, including ElastiCache Redis cluster? I'm assuming there might be some connectivity/permissions issue that you might want to troubleshoot.

Thanks,
Ashish

**Comment by tvytrykush** [comment]
Hi @ashishdhingra, I'm pretty sure the connectivity is fine, because lambda can connect to redis and it does write _something_ to cache, but not what is expected. But if of any interest here's the config.
<img width="1274" alt="redis-elasticache" src="https://github.com/aws/aws-lambda-dotnet/assets/74008560/74e1b9ac-e59d-4afd-bd3f-99cf431ab918">

and SAM for Lambda:
```yaml
# This AWS SAM template has been generated from your function's configuration. If
# your function has one or more triggers, note that the AWS resources associated
# with these triggers aren't fully specified in this template and include
# placeholder values. Open this template in AWS Application Composer or your
# favorite IDE and modify it to specify a serverless application with other AWS
# resources.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  mylambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 100
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: Nonprod
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: >-
        <edited>:amd64_latest
      PackageType: Image
      Policies:
        - Statement:
            - Sid: AWSLambdaVPCAccessExecutionPermissions
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeSubnets
                - ec2:DeleteNetworkInterface
                - ec2:AssignPrivateIpAddresses
                - ec2:UnassignPrivateIpAddresses
              Resource: '*'
            - Sid: BasePermissions
              Effect: Allow
              Action:
                - secretsmanager:*
                - cloudformation:CreateChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:DescribeStackResource
                - cloudformation:DescribeStacks
                - cloudformation:ExecuteChangeSet
                - docdb-elastic:GetCluster
                - docdb-elastic:ListClusters
                - ec2:DescribeSecurityGroups
                - ec2:DescribeSubnets
                - ec2:DescribeVpcs
                - kms:DescribeKey
                - kms:ListAliases
                - kms:ListKeys
                - lambda:ListFunctions
                - rds:DescribeDBClusters
                - rds:DescribeDBInstances
                - redshift:DescribeClusters
                - redshift-serverless:ListWorkgroups
                - redshift-serverless:GetNamespace
                - tag:GetResources
              Resource: '*'
            - Sid: LambdaPermissions
              Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:CreateFunction
                - lambda:GetFunction
                - lambda:InvokeFunction
                - lambda:UpdateFunctionConfiguration
              Resource: arn:aws:lambda:*:*:function:SecretsManager*
            - Sid: SARPermissions
              Effect: Allow
              Action:
                - serverlessrepo:CreateCloudFormationChangeSet
                - serverlessrepo:GetApplication
              Resource: arn:aws:serverlessrepo:*:*:applications/SecretsManager*
            - Sid: S3Permissions
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Sid: ElastiCacheManagementActions
              Effect: Allow
              Action:
                - elasticache:*
              Resource: '*'
            - Sid: CreateServiceLinkedRole
              Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
              Resource: >-
                arn:aws:iam::*:role/aws-service-role/elasticache.amazonaws.com/AWSServiceRoleForElastiCache
              Condition:
                StringLike:
                  iam:AWSServiceName: elasticache.amazonaws.com
            - Sid: CreateVPCEndpoints
              Effect: Allow
              Action:
                - ec2:CreateVpcEndpoint
              Resource: arn:aws:ec2:*:*:vpc-endpoint/*
              Condition:
                StringLike:
                  ec2:VpceServiceName: com.amazonaws.elasticache.serverless.*
            - Sid: AllowAccessToElastiCacheTaggedVpcEndpoints
              Effect: Allow
              Action:
                - ec2:CreateVpcEndpoint
              NotResource: arn:aws:ec2:*:*:vpc-endpoint/*
            - Sid: TagVPCEndpointsOnCreation
              Effect: Allow
              Action:
                - ec2:CreateTags
              Resource: arn:aws:ec2:*:*:vpc-endpoint/*
              Condition:
                StringEquals:
                  ec2:CreateAction: CreateVpcEndpoint
                  aws:RequestTag/AmazonElastiCacheManaged: 'true'
            - Sid: AllowAccessToEc2
              Effect: Allow
              Action:
                - ec2:DescribeVpcs
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
              Resource: '*'
            - Sid: AllowAccessToKMS
              Effect: Allow
              Action:
                - kms:DescribeKey
                - kms:ListAliases
                - kms:ListKeys
              Resource: '*'
            - Sid: AllowAccessToCloudWatch
              Effect: Allow
              Action:
                - cloudwatch:GetMetricStatistics
                - cloudwatch:GetMetricData
              Resource: '*'
            - Sid: AllowAccessToAutoScaling
              Effect: Allow
              Action:
                - application-autoscaling:DescribeScalableTargets
                - application-autoscaling:DescribeScheduledActions
                - application-autoscaling:DescribeScalingPolicies
                - application-autoscaling:DescribeScalingActivities
              Resource: '*'
            - Sid: DescribeLogGroups
              Effect: Allow
              Action:
                - logs:DescribeLogGroups
              Resource: '*'
            - Sid: ListLogDeliveryStreams
              Effect: Allow
              Action:
                - firehose:ListDeliveryStreams
              Resource: '*'
            - Sid: DescribeS3Buckets
              Effect: Allow
              Action:
                - s3:ListAllMyBuckets
              Resource: '*'
            - Sid: AllowAccessToOutposts
              Effect: Allow
              Action:
                - outposts:ListOutposts
              Resource: '*'
            - Sid: AllowAccessToSNS
              Effect: Allow
              Action:
                - sns:ListTopics
              Resource: '*'
      ReservedConcurrentExecutions: 10
      SnapStart:
        ApplyOn: None
      VpcConfig:
        SecurityGroupIds:
          - sg-<edited>
        SubnetIds:
          - subnet-<edited>
          - subnet-<edited>
          - subnet-<edited>
        Ipv6AllowedForDualStack: false
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

```
