### ISSUE TITLE
In Annotations Framework, is it possible to set up a custom domain for an HttpApi in your serverless.template?

### ISSUE THREAD

**Issue by ashishdhingra** [aws/aws-lambda-dotnet#1703]
### Discussed in https://github.com/aws/aws-lambda-dotnet/discussions/1681

<div type='discussions-op-text'>

<sup>Originally posted by **lorenh** February 26, 2024</sup>
We are used to setting up custom domains for our REST APIs in the aspnetcore webapi-style projects directly in our serverless templates using something like this (where all the !Ref's are passed in as parameters). Now I'm experimenting with the "HttpApi" and don't see the equivalent Domain settings under it as I saw under "Api"

```
:
Globals:
  Api:
    Domain:
      DomainName: !Ref DomainName
      CertificateArn: !Ref CertificateArn
      EndpointConfiguration: EDGE
      Route53:
        HostedZoneName: !Ref HostedZoneName
```

HttpApi appears to only support AccessLogSettings, Auth, StageVariables and Tags.  I guess this is more of a SAM or CloudFormation question, but was hoping someone out here has figured out a way to configure it directly in your serverless template.

```
:
Globals:
  HttpApi:
    Domain:  <=====   ERROR
      DomainName: !Ref DomainName
      CertificateArn: !Ref CertificateArn
      EndpointConfiguration: EDGE
      Route53:
        HostedZoneName: !Ref HostedZoneName
```</div>
