### ISSUE TITLE
.NETCORE 2.1 Lambda Invocation throws "Could not find the required deps.json."

### ISSUE THREAD

**Issue by drvora** [aws/aws-lambda-dotnet#402]
We have .NET 2.1 project which deploys fine from VS but when we use S3, codePipeline (codeBuild) and cloudFormation to deploy it throws this error:

Could not find the required AssemblyName.deps.json. This file should be present at the root of the deployment package.: LambdaException

We have this file in the root folder of the zip and AssemblyName is matches the filename as well. Please help.

**Comment by vellozzi** [comment]
If you're creating the zip on windows it might be a permissions issue when it unzips on linux.
How are you packaging the zip file?  (what tool, what OS)

**Comment by drvora** [comment]
AWS codeBuild project is packaging the zip on Ubuntu OS.

**Comment by vellozzi** [comment]
OK.  Using the zip utility on Ubuntu, or using dotnet lambda CLI tool, or something else?

**Comment by drvora** [comment]
I am not sure how codeBuild does it. Here our buildspec.yaml file

version: 0.2

phases:
  pre_build:
    commands:
       - umask 0002
       - echo Restore started on `date`
       - dotnet restore <csproj file>
  build:
    commands:
       - umask 0002
       - echo Publish started on `date`
       - dotnet publish -c release -o ../../build_output <csproj file>
       - aws cloudformation package --template-file serverless.template --s3-bucket <bucketName> --output-template-file outputSamTemplate.yaml
       - mv outputSamTemplate.yaml ./build_output/
       - chmod 777 -R ./build_output/
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: 'build_output'

**Comment by vellozzi** [comment]
You're referencing ../../build_output in your dotnet publish but then you're referencing ../build_output in later commands.  
Could that be it?

If that's not it, have you downloaded the zip file from S3 and manually inspected it?

**Comment by drvora** [comment]
That's not it. I have downloaded the zip file from S3 and can confirm that project is structured correctly. It deploys fine without any issues. Lambda throws exception when trying invoke an API via URL.

**Comment by drvora** [comment]
I have just tried using Windows Server Image in codeBuild instead of Ubuntu OS. Got the same error.

**Comment by normj** [comment]
Instead of using the AWS cli could you try using our Amazon.Lambda.Tools tools package? Then you would be using the same code we use inside Visual Studio. Here is a sample buildspec.yml that I wrote for my re:Invent talk last year.

```yml
version: 0.2

env:
    parameter-store:
        S3_BUCKET: "/CloudMosaic/prod/AppOptions/MosaicStorageBucket"
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - cd ./Code/CloudMosaic/GalleryGenerator/ProcessRawImage
      - dotnet lambda package-ci --serverless-template serverless.template --output-template updated.template --s3-bucket $S3_BUCKET --s3-prefix ProcessRawImage
artifacts:
  files:
    - ./Code/CloudMosaic/GalleryGenerator/ProcessRawImage/updated.template
  discard-paths: yes
```
