### ISSUE TITLE
Can't set Code URI for nested stack

### ISSUE THREAD

**Issue by cidthecoatrack** [aws/aws-lambda-dotnet#526]
I am using the following command to deploy a serverless application:

```
dotnet lambda deploy-serverless `
  --s3-bucket $envName `
  --stack-name $envName `
  --profile $awsProfile `
  --region "us-east-1" `
  --framework "netcoreapp2.1" `
  --template "$dir\serverless.yaml" `
  --template-parameters "EnvironmentName=$env;SharedStackName=$sharedStackName;CouchbaseServers=$couchbaseServer;CouchbaseUsername=$couchbaseUsername;CouchbasePassword=$couchbasePassword;RedisServer=$redisConnection;AppBaseUrl=$appBaseUrl" `
  --package $package
```

This works for the most part, but a new addition has added a nested stack within the template:

```
  UploadsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SharedStackName: !Ref SharedStackName
        EnvironmentName: !Ref EnvironmentName
        CouchbaseServers: !Ref CouchbaseServers
        CouchbaseUsername: !Ref CouchbaseUsername
        CouchbasePassword: !Ref CouchbasePassword
        BuildVersion: !Ref BuildVersion
        AppBaseUrl: !Ref AppBaseUrl
        AwsRegion: !Ref AwsRegion
        BlitlineJpegMiniIntegration: !Ref BlitlineJpegMiniIntegration
        SenderEmail: !Ref SenderEmail
        ExifToolLambdaLayer: !Ref ExifToolLambdaLayer
        HeartbeatDuration: !Ref HeartbeatDuration
        RedisServer: !Ref RedisServer
        AssetsS3Bucket: !Ref AssetsS3Bucket
        PreviewsS3Bucket: !Ref PreviewsS3Bucket
        AttachmentsS3Bucket: !Ref AttachmentsS3Bucket
        BlitlineBufferingQueueUrl: !Ref BlitlineBufferingQueue
        BlitlineBufferingQueueArn:
          Fn::GetAtt:
            - "BlitlineBufferingQueue"
            - "Arn"
        AssetFileUploadedQueueArn:
          Fn::GetAtt:
            - "AssetFileUploadedQueue"
            - "Arn"
        AttachmentFileUploadedQueueArn:
          Fn::GetAtt:
            - "AttachmentFileUploadedQueue"
            - "Arn"
      TemplateURL: !Join ["", ["https://s3.amazonaws.com/globaleditapi-assets-", !Ref EnvironmentName, "/serverless-uploads.yaml"]]
```

This nested stack shares the same code base as the parent stack - they are in fact related, but have to be split into nested stacks because of the 460Kb size restriction.  This is also fine - except that when I get to the following bit in the nested stack:

```
Globals:
  Function:
    CodeUri: './bin/Debug/netcoreapp2.1/Assets.zip'
    Runtime: dotnetcore2.1
    MemorySize: 256
    Timeout: 30
    Tracing: Active
```

The deployment complains that the `CodeUri` is not valid.  The zip package generated by the `dotnet lambda deploy-serverless` is `https://[my bucket]/globaledit-api-asset-lambdas-637033774610695901.zip`, but the name of the zip is auto-geneerated by the lambda compilation.  I do not know how to access that as a variable, in order to pass it down to the nested stack and set it as the code Uri.  In the parent stack, the `CodeUri` is the same (`'./bin/Debug/netcoreapp2.1/Assets.zip'`), but it is obviously being replaced/updated with the uploaded path from the compilation/zipping step.  However, if I look in the CloudFormation template, the raw template still contains the original, non-S3 path.

All that to say, I need to be able to access the `CodeUri` value that is given to the template when `dotnet lambda deploy-serverless` runs, since the path is custom per deployment.  I cannot currently do this.  I also need a way to give that to the nested stack as a parameter - which, since I have to set template parameters before the compilation step occurs, seems problematic at best, impossible at worst.  Might there be a way for deployment to detect a nested stack and replace the `CodeUri` in the nested stack the same way it does in the parent stack?  Obviously it would have to be configurable, since not everyone wants their stacks to share code uris
