### ISSUE TITLE
!Sub not supported in template file

### ISSUE THREAD

**Issue by tmay57** [aws/aws-lambda-dotnet#718]
## Description

```
Resources:
  GetBlogs:
    Properties:
      FunctionName: !Sub ${AWS::StackName}
```
Generates an error: Error parsing JSON CloudFormation Template. ... : Exception during deserialization
Using Fn::Sub: also fails.
This is true for both JSON and Yaml template file formats.

## Reproduction Steps
Create the sample Blogger application. Add the FunctionName property as shown above. Try to publish.
BTW - using  the SAM CLI works just fine as does Stackery.io. My assumption is that any template that is valid for the SAM CLI should be valid with the VS extension.

### Logs
NA

### Environment
* OS Info: Windows 10 Pro
* Build Environment: Visual Studio - 16.6.5
* AWS Toolkit version 1.18.1.0

## Resolution
---

This is a :bug: bug-report
