### ISSUE TITLE
CamelCaseLambdaJsonSerializer not using camelCase to serialize responses

### ISSUE THREAD

**Issue by mmillican** [aws/aws-lambda-dotnet#743]
## Description
Not sure if I'm missing something, but when using the assembly attribute for `CamelCaseLambdaJsonSerializer`, I'm not seeing my responses be returned in camel casing. Here's a partial code sample of what I'm doing:

```c#
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.CamelCaseLambdaJsonSerializer))]
namespace MyProject.Api
{
    public partial class ImageFunctions
    {
        public async Task<APIGatewayProxyResponse> GetImagesAsync(APIGatewayProxyRequest request, ILambdaContext context)
        {
            var imageTypeQuery = request?.QueryStringParameters["type"];

           var images = GetMyImages(); // Simplified

            context.Logger.LogLine($"Found {images.Count()} images");

            var response = new APIGatewayProxyResponse
            {
                StatusCode = (int)HttpStatusCode.OK,
                Body = JsonSerializer.Serialize(images),
                Headers = _defaultHeaders
            };

            return response;
        }
}
```

The response I'm getting looks like this:

```
[
  {
    "Id": "4a8d207c-4c64-407b-9923-fce3b1cdb4f7",
    "UploadedOn": "2020-09-30T01:33:56.213+00:00",
    "Type": "phone",
    "UserName": "test",
    "FileName": "4a8d207c-4c64-407b-9923-fce3b1cdb4f7.jpg",
    "IsPublished": false
  },
  {
    "Id": "2f1d1cab-7914-4a5d-b025-c009db5e68f9",
    "UploadedOn": "2020-09-30T01:42:33.202+00:00",
    "Type": "phone",
    "UserName": "test",
    "FileName": "2f1d1cab-7914-4a5d-b025-c009db5e68f9.jpg",
    "IsPublished": false
  },
]

```

Is it expected that I serialize my response separately using camelCasing? I saw [this blog post](https://aws.amazon.com/blogs/developer/one-month-update-to-net-core-3-1-lambda/) which seems like it was recently fixed, but not seeing that here.

For more context, here's the part of my CloudFormation stack that is creating this function:

```yaml
GetImagesApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'MyApi.Api::MyApi.Api.ImageFunctions::GetImagesAsync'
      Runtime: dotnetcore3.1
      CodeUri: './src/MyApi.Api'
      Description: Get a list of images
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt ApiLambdaRole.Arn
      Policies:
        - AWSLambdaFullAccess
      Environment:
        Variables:
          ImageTable: !Ref ImageTable
          BucketName: !Ref ContentBucket
      Events:
        GetList:
          Type: Api
          Properties:
            Path: /images
            Method: GET
            RequestParameters:
              - method.request.querystring.type
            RestApiId:
              Ref: ApiGatewayApi
```

### Environment
* Build Version: Amazon.Lambda.Serialization.SystemTextJson v2.0.2
* OS Info: Windows 10, deployed to a Lambda function with API Gateway
* Build Environment: VS Code
* Targeted .NET Platform:  netcoreapp3.1 on Lambda

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

Happy to help resolve the issue if there is indeed one, but from looking at the code in the repo, I don't see any immediate issues.

---

This is a :bug: bug-report
