### ISSUE TITLE
Controller endpoint not found when invoking lambda (MapGet/MapPost works)

### ISSUE THREAD

**Issue by mdrgeniebelt** [aws/aws-lambda-dotnet#856]
## The Question
Hello, I'm trying to use AWS lambda with .net core using SAM to deploy it to cloud. Almost everything works but there is no thing I'm unable to figure out so I figured I'd ask here :) 

So basically I have Hello World .net 5 application with SAM template, I'll past a bit of code so it's easier for you to see what I mean

Startup.cs

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
}

public void Configure(IApplicationBuilder app)
{
    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
        endpoints.MapGet("test", async context =>
        {
            await context.Response.WriteAsJsonAsync(new
            {
                Message = "Hello World from GET!"
            });
        });

        endpoints.MapPost("test", async context =>
        {
            await context.Response.WriteAsJsonAsync(new
            {
                Message = "Hello World from POST!"
            });
        });
    });
}
```

Controller
```csharp
[Route("api/todo")]
public class TodoController : ControllerBase
{
    [HttpGet]
    public IActionResult Get()
    {
        return Ok(new
        {
            Message = "Response from GET",
        });
    }
    
    [HttpPost]
    public IActionResult Post()
    {
        return Ok(new
        {
            Message = "Response from POST",
        });
    }
}
```

LambdaEntryPoint
```csharp
using Amazon.Lambda.AspNetCoreServer;
using Amazon.Lambda.Core;
using Microsoft.AspNetCore.Hosting;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.CamelCaseLambdaJsonSerializer))]
namespace HelloWorld
{
    public class LambdaEntryPoint : APIGatewayProxyFunction
    {
        protected override void Init(IWebHostBuilder builder)
        {
            builder.UseStartup<Startup>();
        }
    }
}
```

Now SAM template:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: dotnet5.0-v1
      DockerContext: ./src/HelloWorld
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run
```

Now when I use postman to call my lambda everything works fine for `test` endpoint 

so: 
GET https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test returns 

```json
{
    "message": "Hello World from GET!"
}
```

but if I try to call 

GET https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/todo I get 404 in response, I can see in logs that my LambdaEntryPoint is executed but for some reasons my endpoint is not being properly resolved. This is probably a very silly bug/misconfiguration but I tried different controllers with different paths and tried to call other paths from postman but nothing works...

Any ideas? 

Thanks in advance!
