### ISSUE TITLE
Serverless.template (Lambda Layers) support for pre-jitting .NET assemblies

### ISSUE THREAD

**Issue by bschaatsbergen** [aws/aws-lambda-dotnet#896]
It would be nice if we could declare a Lambda Layer in the serverless template that will be pre-jitted and packaged as a runtime package store. 

At the moment it requires us to first run something like this: `dotnet lambda publish-layer Dependencies --layer-type runtime-package-store --s3-bucket my-lambda-layer-bucket --framework netcoreapp3.1 --enable-package-optimization true`.

Then get the ARN from the output and pass it to the serverless.template. Also in order use `--enable-package-optimization` it requires to be ran from an Amazon Linux AMI.

It would be very nice if we could declare a runtime package store as Lambda layer like the following (psuedo):

```
MyLambdaLayer
 Type: AWS::Serverless::LayerVersion
  Properties:
    LayerName: MyLayer
    Description: Layer description
    ContentUri: 'src/Dependencies/Dependencies.csproj'
    Bucket: !Ref MyLayersBucket
    EnableOptimizedPackages: True
    LayerType: RuntimePackageStore
    Framework: netcoreapp3.1
    CompatibleRuntimes:
      - dotnetcore3.1
    LicenseInfo: 'Available under the MIT-0 license.'
    RetentionPolicy: Retain
```
And ref this layer in our Lambda function by ARN.

```
MyLambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: .
    Handler: my_handler
    Runtime: dotnetcore3.1
    Layers:
        - !Ref MyLambdaLayer
```

Currently the pre jitting of .NET assemblies is not that often used and it could greatly encourage .NET developers to use this feature by adding this feature. cc @normj, thoughts?
